### ISSUE TITLE
是否有启动的说明文档

### ISSUE THREAD

**Issue by YDLinStars** [DengSchoo/vxSocialMinProgram#1]
你好，对你的项目很感兴趣，是否有启动的说明文档能协助我启动这个项目 谢谢

**Comment by DengSchoo** [comment]
okkk, Issue已收到，晚点叭，有场笔试，今晚晚点或者明天，启动说明文档也会更新在readme.md里面，注意查收^-^。（欢迎star 小声bb。

**Comment by DengSchoo** [comment]
> 你好，对你的项目很感兴趣，是否有启动的说明文档能协助我启动这个项目 谢谢
okkk, Issue已收到，晚点叭，有场笔试，今晚晚点或者明天，启动说明文档也会更新在readme.md里面，注意查收^-^。（欢迎star 小声bb。

**Comment by YDLinStars** [comment]
非常感谢，可是在文档中，没有找到数据库的说明 能否提供一份说明文档呢？

**Comment by DengSchoo** [comment]
> 非常感谢，可是在文档中，没有找到数据库的说明 能否提供一份说明文档呢？

已经更新数据库说明文档

**Comment by YDLinStars** [comment]
非常感谢 问题得到解决了
