### ISSUE TITLE
关于新版本登录问题

### ISSUE THREAD

**Issue by YDLinStars** [DengSchoo/vxSocialMinProgram#2]
2021.4.13微信授权登录部分的open-type开放数据
只能够获得open_id了 以及匿名信息
所以接口的获取需要重新写一下
做一下事件绑定
index.wxml
`
    <view style="padding-top:5%" class="padding flex flex-direction btnlogin">
        <button style="flex-basis:20%;font-size:15px"  class="cu-btn bg-green  button-hover animation-{{animation==item.name?item.name:''}} margin-sm basis-sm shadow" bindtap="getUserProfile" data-class="{{item.name}}" wx:for="{{list}}" wx:key="index"  open-type="getUserInfo" bindgetuserinfo="handleUserInfo" role="button" aria-disabled="false">
            {{btninfo}}
        </button>
    </view>

`
通过handleUserInfo获取openid 和原先的步骤一样
但是只需要加入到全局变量中就可以

最后获取授权登录的方式
`
    getUserProfile(e) {
    // 推荐使用wx.getUserProfile获取用户信息，开发者每次通过该接口获取用户个人信息均需用户确认
    // 开发者妥善保管用户快速填写的头像昵称，避免重复弹窗
    console.log('openid:'+app.globalData['openid'])
    wx.getUserProfile({
      desc: '用于完善会员资料', // 声明获取用户个人信息后的用途，后续会展示在弹窗中，请谨慎填写
      success: (res) => {
        this.setData({
          userInfo: res.userInfo,
          hasUserInfo: true
        })
      console.log(res)
      app.globalData['userPhoto'] = res.userInfo.avatarUrl;
      app.globalData['nickName'] = res.userInfo.nickName;
      app.globalData['gender'] = res.userInfo.gender;
      wx.setStorageSync('userinfo', res.userInfo);
      db.collection('users').where({
        _openid : app.globalData['openid']
      }).get().then((res)=>{
        if (res.data.length == 0) {
          wx.reLaunch({
          url: '../register/register',
          });
          return
        } else 
          {
            
            if (this.data.userinfo.length != 0) {
              app.globalData["permission"] = true
            }

            if (app.globalData["permission"] == true) {
              app.userInfo = Object.assign(app.userInfo, res.data[0]);
              wx.reLaunch({
                url: '../index/index',
              })
              return;
            }
             
             this.setData({
              Img:app.globalData['userPhoto'],
              btninfo:app.globalData['nickName'] + " 现在开始",
              //permission:true
              })
              app.globalData["permission"] = true
          } 
      })
      },
      fail: res => {
        //拒绝授权
        wx.showToast({
          title: '您拒绝了授权',
          icon: 'none'
        })
        return;
      }
    })
   },
`

Q1： 关于授权登录的方式 是否还有其他解决办法 
目前通过调用两个函数 执行顺序无法控制，是否能在一个函数中解决上述问题

**Comment by DengSchoo** [comment]
问题排版有点乱，要问哪一块的代码问题不是特别清楚。
当时开发时对于用户授权登录这里：
- 我们考虑的需求是两种用户：1、第一次登录的用户，对于第一次登录的用户，我们就需要展示第一次登录的界面，并将数据缓存到用户本地缓存中。2、第二次登录的用户就不需要再走授权，可以根据本地是否有缓存来判断是否是第一次登录，前端页面就直接展示他的信息就可以了也就是`btninfo:app.globalData['nickName'] + " 现在开始"`
- 执行顺序无法控制具体指的是什么 synchronous与asynchronous的问题么。可以ES7提供的`async/await`机制可以实现。
这里给你提供一个blog可以参考一下：`https://www.cnblogs.com/IT-CPC/p/10898871.html`，对js同步异步有解释，也有具体代码实现。**希望可以对你有帮助**
