### ISSUE TITLE
大佬我要求助

### ISSUE THREAD

**Issue by cowardcat** [DengSchoo/vxSocialMinProgram#3]
大佬，你好！我是一名学生，可以一份完整版的吗？我把上面那个运行后才发现是有一大部分功能是缺陷的，当然如果需要支付点代价，我也是能接受的，毕竟知识是财富。
如果您同意分享
可否联系一下我QQ390477024
可否发到我的QQ邮箱：390477024@qq.com
感激不尽

**Comment by DengSchoo** [comment]
此版本不再维护，此为开源作品， 不完整坑很多。不过里面涉及到的框架和对应框架使用可以作为参考，如有不清楚查看vx官方文档或者对应框架文档。
